# Generated by Django 4.2.2 on 2023-06-28 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('kind', models.CharField(choices=[('apartment', 'Апартамент'), ('de_luxe', 'Номер повышенной комфортности'), ('file_and_text', 'Семейный номер'), ('default', 'Не выбрано')], default='default', max_length=50, verbose_name='Вид')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Стоимость')),
                ('number_of_beds', models.PositiveIntegerField(default=0, verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['number'],
            },
        ),
    ]
