version: '3.8'

services:
  db:
    image: postgres:13.0
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - reservation-app


volumes:
  postgres_data:

networks:
  reservation-app:
    driver: bridge
